# Generated by Django 2.0.5 on 2018-06-15 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_auto_20180608_1938'),
    ]

    operations = [
        migrations.CreateModel(
            name='Img',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(
                    height_field=200, upload_to='', width_field=200)),
            ],
        ),
        migrations.AddField(
            model_name='articles',
            name='image',
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, to='news.Img'),
        ),
    ]
