# Generated by Django 2.0.7 on 2018-07-16 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': 'comment',
                     'verbose_name_plural': 'comments'},
        ),
        migrations.AlterField(
            model_name='articles',
            name='image',
            field=models.ImageField(default=1, upload_to='media/%Y/%m/%d'),
            preserve_default=False,
        ),
    ]
