# Generated by Django 2.0.7 on 2018-08-12 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0009_auto_20180726_1751'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='url',
            field=models.TextField(blank=True, null=True, verbose_name='Урлы'),
        ),
    ]
