# Generated by Django 2.0.7 on 2018-08-15 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0010_articles_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='image_link',
            field=models.TextField(blank=True, null=True,
                                   verbose_name='Cсылки на картинки'),
        ),
    ]
