# Generated by Django 2.0.7 on 2018-08-15 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0011_articles_image_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='image',
            field=models.ImageField(blank=True, help_text='150x150px',
                                    upload_to='images/', verbose_name='Ссылка картинки'),
        ),
    ]
