# Generated by Django 2.1 on 2018-10-10 15:18

from django.db import migrations, models
import django.db.models.deletion
import news.models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0014_auto_20180827_1714'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleStatistic',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(
                    default=news.models.default_date, verbose_name='Дата')),
                ('views', models.IntegerField(default=0, verbose_name='Просмотры')),
                ('article', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='news.Articles')),
            ],
            options={
                'db_table': 'ArticleStatistic',
            },
        ),
    ]
