# Generated by Django 2.1 on 2018-10-11 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0015_articlestatistic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articlestatistic',
            name='article',
        ),
        migrations.DeleteModel(
            name='ArticleStatistic',
        ),
    ]
