# Generated by Django 2.1.7 on 2019-03-09 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0016_auto_20181011_1500'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='author',
            field=models.TextField(blank=True, null=True, verbose_name='Автор'),
        ),
    ]
