# Generated by Django 2.1.7 on 2019-03-24 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0017_articles_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='post',
        ),
        migrations.RemoveField(
            model_name='articles',
            name='dislikes',
        ),
        migrations.RemoveField(
            model_name='articles',
            name='likes',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
